version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - socket_server
    volumes:
      - .:/app
    command: ["python", "main.py"]

  socket_server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: ["python", "socket_server.py"]
    environment:
      - MONGO_URL=mongodb://mongo:27017/

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
